//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptingMaui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptingMaui.Resources.Strings.AppResources.es", typeof(AppResources_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acento:.
        /// </summary>
        internal static string Accent_ {
            get {
                return ResourceManager.GetString("Accent:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objetos personales.
        /// </summary>
        internal static string accesories {
            get {
                return ResourceManager.GetString("accesories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjetivos.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todas las palabras.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mundo animal.
        /// </summary>
        internal static string animal_world {
            get {
                return ResourceManager.GetString("animal world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases básicas.
        /// </summary>
        internal static string basic_phrases {
            get {
                return ResourceManager.GetString("basic phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to habitación y baño.
        /// </summary>
        internal static string bed_and_bath {
            get {
                return ResourceManager.GetString("bed and bath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejor resultado:.
        /// </summary>
        internal static string Best_score_ {
            get {
                return ResourceManager.GetString("Best score:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partes del cuerpo.
        /// </summary>
        internal static string body_parts {
            get {
                return ResourceManager.GetString("body parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adiós.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendario, tiempo.
        /// </summary>
        internal static string calendar__time {
            get {
                return ResourceManager.GetString("calendar, time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprueba tu conexión a Internet.
        /// </summary>
        internal static string Check_your_internet_connection {
            get {
                return ResourceManager.GetString("Check your internet connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ropa.
        /// </summary>
        internal static string clothing {
            get {
                return ResourceManager.GetString("clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colores, figuras.
        /// </summary>
        internal static string colors__figures {
            get {
                return ResourceManager.GetString("colors, figures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto:.
        /// </summary>
        internal static string Correct_ {
            get {
                return ResourceManager.GetString("Correct:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correctos: {0}% ({1}/{2}).
        /// </summary>
        internal static string Correct___0_____1___2__ {
            get {
                return ResourceManager.GetString("Correct: {0}% ({1}/{2})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to países.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medio ambiente.
        /// </summary>
        internal static string environment {
            get {
                return ResourceManager.GetString("environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Excelente!.
        /// </summary>
        internal static string Excellent_ {
            get {
                return ResourceManager.GetString("Excellent!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falso.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to familia y niños.
        /// </summary>
        internal static string family_and_kids {
            get {
                return ResourceManager.GetString("family and kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminado.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases para coquetear.
        /// </summary>
        internal static string flirting_phrases {
            get {
                return ResourceManager.GetString("flirting phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аlimentos y bebida.
        /// </summary>
        internal static string food_and_beverage {
            get {
                return ResourceManager.GetString("food and beverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frutas y verduras.
        /// </summary>
        internal static string fruits_and_vegetables {
            get {
                return ResourceManager.GetString("fruits and vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hola.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hobby, música, ajedrez.
        /// </summary>
        internal static string hobby__music__chess {
            get {
                return ResourceManager.GetString("hobby, music, chess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hogar.
        /// </summary>
        internal static string household {
            get {
                return ResourceManager.GetString("household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imágenes.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cocina.
        /// </summary>
        internal static string kitchen {
            get {
                return ResourceManager.GetString("kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma a aprender:.
        /// </summary>
        internal static string Language_to_learn_ {
            get {
                return ResourceManager.GetString("Language to learn:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprender.
        /// </summary>
        internal static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprender.
        /// </summary>
        internal static string Learn_wide {
            get {
                return ResourceManager.GetString("Learn_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se reconoció lo que dijiste.
        /// </summary>
        internal static string No_speech_was_recognized {
            get {
                return ResourceManager.GetString("No speech was recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to números y matemáticas.
        /// </summary>
        internal static string numbers_and_math {
            get {
                return ResourceManager.GetString("numbers and math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parte de la palabra o ID.
        /// </summary>
        internal static string Part_of_word_or_word_id {
            get {
                return ResourceManager.GetString("Part of word or word id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frases.
        /// </summary>
        internal static string Phrases {
            get {
                return ResourceManager.GetString("Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases para saludar.
        /// </summary>
        internal static string phrases_greetings {
            get {
                return ResourceManager.GetString("phrases greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases en hotel.
        /// </summary>
        internal static string phrases_in_hotel {
            get {
                return ResourceManager.GetString("phrases in hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases en restaurante.
        /// </summary>
        internal static string phrases_in_restaurant {
            get {
                return ResourceManager.GetString("phrases in restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frases viajando.
        /// </summary>
        internal static string phrases_traveling {
            get {
                return ResourceManager.GetString("phrases traveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad de reproducción:.
        /// </summary>
        internal static string Play_Rate_ {
            get {
                return ResourceManager.GetString("Play Rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, espera....
        /// </summary>
        internal static string Please_wait___ {
            get {
                return ResourceManager.GetString("Please wait...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preposiciones.
        /// </summary>
        internal static string prepositions {
            get {
                return ResourceManager.GetString("prepositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profesiones.
        /// </summary>
        internal static string profession {
            get {
                return ResourceManager.GetString("profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de prueba:.
        /// </summary>
        internal static string Quiz_Mode_ {
            get {
                return ResourceManager.GetString("Quiz Mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de prueba:.
        /// </summary>
        internal static string Quiz_Type_ {
            get {
                return ResourceManager.GetString("Quiz Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prueba.
        /// </summary>
        internal static string Quiz_wide {
            get {
                return ResourceManager.GetString("Quiz_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabras en prueba:.
        /// </summary>
        internal static string Quiz_Words_ {
            get {
                return ResourceManager.GetString("Quiz Words:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to escuela y oficina.
        /// </summary>
        internal static string school_and_office {
            get {
                return ResourceManager.GetString("school and office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Categoría.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        internal static string Settings_wide {
            get {
                return ResourceManager.GetString("Settings_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonido:.
        /// </summary>
        internal static string Sound_ {
            get {
                return ResourceManager.GetString("Sound:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habla:.
        /// </summary>
        internal static string Speak_ {
            get {
                return ResourceManager.GetString("Speak:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hablar.
        /// </summary>
        internal static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapidez de voz:.
        /// </summary>
        internal static string Speech_Rate_ {
            get {
                return ResourceManager.GetString("Speech Rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deporte.
        /// </summary>
        internal static string sport {
            get {
                return ResourceManager.GetString("sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herramientas y aparatos.
        /// </summary>
        internal static string tools_and_appliances {
            get {
                return ResourceManager.GetString("tools and appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traducir.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traducir a:.
        /// </summary>
        internal static string Translate_to_ {
            get {
                return ResourceManager.GetString("Translate to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transporte.
        /// </summary>
        internal static string transport {
            get {
                return ResourceManager.GetString("transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verbos.
        /// </summary>
        internal static string verbs {
            get {
                return ResourceManager.GetString("verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabra:.
        /// </summary>
        internal static string Word_ {
            get {
                return ResourceManager.GetString("Word:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabra {0}/{1}.
        /// </summary>
        internal static string Word__0___1_ {
            get {
                return ResourceManager.GetString("Word {0}/{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar {0}.
        /// </summary>
        internal static string Word_with__0__not_found {
            get {
                return ResourceManager.GetString("Word with {0} not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palabras.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muy bien.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece que no hay micrófono.
        /// </summary>
        internal static string You_don_t_seem_to_have_a_microphone {
            get {
                return ResourceManager.GetString("You don\'t seem to have a microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijiste:.
        /// </summary>
        internal static string You_said_ {
            get {
                return ResourceManager.GetString("You said:", resourceCulture);
            }
        }
    }
}
