//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptingMaui.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptingMaui.Resources.Strings.AppResources.de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akzent:.
        /// </summary>
        internal static string Accent_ {
            get {
                return ResourceManager.GetString("Accent:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zubehör und Accessoires.
        /// </summary>
        internal static string accesories {
            get {
                return ResourceManager.GetString("accesories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjektive.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Wörter.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tierwelt.
        /// </summary>
        internal static string animal_world {
            get {
                return ResourceManager.GetString("animal world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grundlegende Phrasen.
        /// </summary>
        internal static string basic_phrases {
            get {
                return ResourceManager.GetString("basic phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlaf- und Badezimmer.
        /// </summary>
        internal static string bed_and_bath {
            get {
                return ResourceManager.GetString("bed and bath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beste Ergebnis:.
        /// </summary>
        internal static string Best_score_ {
            get {
                return ResourceManager.GetString("Best score:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Körperteile.
        /// </summary>
        internal static string body_parts {
            get {
                return ResourceManager.GetString("body parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Wiedersehen.
        /// </summary>
        internal static string bye {
            get {
                return ResourceManager.GetString("bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalender, Zeit.
        /// </summary>
        internal static string calendar__time {
            get {
                return ResourceManager.GetString("calendar, time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen Sie Ihre Internetverbindung.
        /// </summary>
        internal static string Check_your_internet_connection {
            get {
                return ResourceManager.GetString("Check your internet connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleidung.
        /// </summary>
        internal static string clothing {
            get {
                return ResourceManager.GetString("clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farben, Figuren.
        /// </summary>
        internal static string colors__figures {
            get {
                return ResourceManager.GetString("colors, figures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig:.
        /// </summary>
        internal static string Correct_ {
            get {
                return ResourceManager.GetString("Correct:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richtig: {0}% ({1}/{2}).
        /// </summary>
        internal static string Correct___0_____1___2__ {
            get {
                return ResourceManager.GetString("Correct: {0}% ({1}/{2})", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ländern.
        /// </summary>
        internal static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umwelt.
        /// </summary>
        internal static string environment {
            get {
                return ResourceManager.GetString("environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgezeichnet!.
        /// </summary>
        internal static string Excellent_ {
            get {
                return ResourceManager.GetString("Excellent!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falsch.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familie und Kinder.
        /// </summary>
        internal static string family_and_kids {
            get {
                return ResourceManager.GetString("family and kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrasen zum Flirten.
        /// </summary>
        internal static string flirting_phrases {
            get {
                return ResourceManager.GetString("flirting phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essen und Getränke.
        /// </summary>
        internal static string food_and_beverage {
            get {
                return ResourceManager.GetString("food and beverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Früchte und Gemüse.
        /// </summary>
        internal static string fruits_and_vegetables {
            get {
                return ResourceManager.GetString("fruits and vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby, Musik, Schach.
        /// </summary>
        internal static string hobby__music__chess {
            get {
                return ResourceManager.GetString("hobby, music, chess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haushalt.
        /// </summary>
        internal static string household {
            get {
                return ResourceManager.GetString("household", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilder.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Küche.
        /// </summary>
        internal static string kitchen {
            get {
                return ResourceManager.GetString("kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache zu lernen:.
        /// </summary>
        internal static string Language_to_learn_ {
            get {
                return ResourceManager.GetString("Language to learn:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lernen.
        /// </summary>
        internal static string Learn {
            get {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lernen.
        /// </summary>
        internal static string Learn_wide {
            get {
                return ResourceManager.GetString("Learn_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modus:.
        /// </summary>
        internal static string Mode_ {
            get {
                return ResourceManager.GetString("Mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falsch.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Rede erkannt.
        /// </summary>
        internal static string No_speech_was_recognized {
            get {
                return ResourceManager.GetString("No speech was recognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahlen und Mathe.
        /// </summary>
        internal static string numbers_and_math {
            get {
                return ResourceManager.GetString("numbers and math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil des Wortes oder ID.
        /// </summary>
        internal static string Part_of_word_or_word_id {
            get {
                return ResourceManager.GetString("Part of word or word id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrasen.
        /// </summary>
        internal static string Phrases {
            get {
                return ResourceManager.GetString("Phrases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruß Phrasen.
        /// </summary>
        internal static string phrases_greetings {
            get {
                return ResourceManager.GetString("phrases greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrasen im Hotel.
        /// </summary>
        internal static string phrases_in_hotel {
            get {
                return ResourceManager.GetString("phrases in hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrasen im Restaurant.
        /// </summary>
        internal static string phrases_in_restaurant {
            get {
                return ResourceManager.GetString("phrases in restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrasen in Reisen.
        /// </summary>
        internal static string phrases_traveling {
            get {
                return ResourceManager.GetString("phrases traveling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergaberate:.
        /// </summary>
        internal static string Play_Rate_ {
            get {
                return ResourceManager.GetString("Play Rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte warten Sie....
        /// </summary>
        internal static string Please_wait___ {
            get {
                return ResourceManager.GetString("Please wait...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präpositionen.
        /// </summary>
        internal static string prepositions {
            get {
                return ResourceManager.GetString("prepositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berufe.
        /// </summary>
        internal static string profession {
            get {
                return ResourceManager.GetString("profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Modus:.
        /// </summary>
        internal static string Quiz_Mode_ {
            get {
                return ResourceManager.GetString("Quiz Mode:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Typ:.
        /// </summary>
        internal static string Quiz_Type_ {
            get {
                return ResourceManager.GetString("Quiz Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        internal static string Quiz_wide {
            get {
                return ResourceManager.GetString("Quiz_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Wörter:.
        /// </summary>
        internal static string Quiz_Words_ {
            get {
                return ResourceManager.GetString("Quiz Words:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schule und Büro.
        /// </summary>
        internal static string school_and_office {
            get {
                return ResourceManager.GetString("school and office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie Auswählen.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string Settings_wide {
            get {
                return ResourceManager.GetString("Settings_wide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ton:.
        /// </summary>
        internal static string Sound_ {
            get {
                return ResourceManager.GetString("Sound:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagen Sie:.
        /// </summary>
        internal static string Speak_ {
            get {
                return ResourceManager.GetString("Speak:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sagen.
        /// </summary>
        internal static string Speech {
            get {
                return ResourceManager.GetString("Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprechgeschwindigkeit:.
        /// </summary>
        internal static string Speech_Rate_ {
            get {
                return ResourceManager.GetString("Speech Rate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string sport {
            get {
                return ResourceManager.GetString("sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkzeuge und Geräte.
        /// </summary>
        internal static string tools_and_appliances {
            get {
                return ResourceManager.GetString("tools and appliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzen.
        /// </summary>
        internal static string Translate {
            get {
                return ResourceManager.GetString("Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersetzen in:.
        /// </summary>
        internal static string Translate_to_ {
            get {
                return ResourceManager.GetString("Translate to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkehr.
        /// </summary>
        internal static string transport {
            get {
                return ResourceManager.GetString("transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verben.
        /// </summary>
        internal static string verbs {
            get {
                return ResourceManager.GetString("verbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wort:.
        /// </summary>
        internal static string Word_ {
            get {
                return ResourceManager.GetString("Word:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wort {0}/{1}.
        /// </summary>
        internal static string Word__0___1_ {
            get {
                return ResourceManager.GetString("Word {0}/{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wort mit {0} nicht gefunden.
        /// </summary>
        internal static string Word_with__0__not_found {
            get {
                return ResourceManager.GetString("Word with {0} not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wörter.
        /// </summary>
        internal static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to richtig.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben gesagt:.
        /// </summary>
        internal static string You_said_ {
            get {
                return ResourceManager.GetString("You said:", resourceCulture);
            }
        }
    }
}
